apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: storer-expressapi
  namespace: storer-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/expressapp-quorum
    git: "https://github.com/ragalz/blockchain-automation-framework.git"
    ref: "test"
  releaseName: storerquorum-expressapi
  values:
    nodeName: storer-expressapi
    metadata:
      namespace: storer-quo
    replicaCount: 1
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secret/storer-quo/smartContracts
      serviceaccountname: vault-auth
      keyname: General
      role: vault-role
      authpath: quorumstorer
    images:
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    expressapp:
      serviceType: ClusterIP
      image: index.docker.io/hyperledgerlabs/supplychain_quorum:express_app_latest
      pullPolicy: Always
      pullSecrets: regcred
      nodePorts:
        port: 3000
        targetPort: 3000
        name: tcp
      env:
        geth_address: http://storer.rc.dev2.aws.blockchaincloudpoc-develop.com:15031
        node_subject: O=Storer,OU=Storer,L=40.73/-74/New York,C=US
        node_organization: storer
        node_organization_unit: storer
        protocol: raft
    proxy:
      provider: ambassador
      name: storer
      type: quorum
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
      peer_name: storer
